version: '3'

services:
  my_nginx:
    build: .
    container_name: hello_world

  proxy_server:
    image: ubuntu/nginx
    container_name: server_1
    ports:
      - 80:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - my_nginx
